# Generated by Django 4.1.3 on 2022-11-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_alter_recipe_persons_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
