import './components/_menu-profile.js';
import './components/_short-ingredients.js';
import './components/_menu-more.js';
import './components/_modal.js';
import './components/_scroll-active.js';
import './components/_smooth-scroll.js';
import './components/_new-recipe.js';
import './components/_imageuploader.js';
import './components/_counter.js'
import './components/_input-validate.js';
import './components/_textarea-resize.js';
import './components/_info-avatar.js';
